### ISSUE TITLE
EJB exception being thrown --- app won't deploy in GlassFish 4.1

### ISSUE THREAD

**Issue by tjmarkowitz** [ianhlavats/primefaces-starter#9]
Ian,

The Java 1.8 error seems to be gone now that you've updated the pom.xml file. That's great. However, I still can't get it to deploy properly since when I run it within NetBeans after a fresh **Clean and Build** it consistently throws an EJBException error that appears to be occuring in CountryServiceImpl.java as it tries to call **getCountries( )**. I will attach the complete GlassFish log for you to look over. I think we're getting close here, but we're not quite there yet.

//Ted M.

[primefaces-webapp.glassfish-log.txt](https://github.com/ianhlavats/primefaces-starter/files/601629/primefaces-webapp.glassfish-log.txt)

**Comment by ianhlavats** [comment]
This issue is now resolved. Please use the java8-javaee7-glassfish4 branch.
